version: '3.8'

services:
  risk-sense-ai:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - NEWS_API_KEY=${NEWS_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/api/countries"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s